{
 "title": "camunda",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Job Executor Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "executor_active_threads{name=\"camundaTaskExecutor\"}"
    },
    {
     "expr": "executor_pool_size_threads{name=\"camundaTaskExecutor\"}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "job_executions_successful_Number_of_jobs{instance=\"camunda-spring:8080\"}"
    },
    {
     "expr": "job_executions_failed_Number_of_jobs{instance=\"camunda-spring:8080\"}"
    }
   ]
  },
  {
   "title": "Job Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jobs_due" }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "job_executions_successful_Number_of_jobs"
    },
    {
     "expr": "job_executions_failed_Number_of_jobs"
    }
   ]
  }
 ]
}